apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello
spec:
  containers:
  - image: nginx
    name: hello-pod
    resources: {}
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: hello-config-volume
  volumes:
  - name: hello-config-volume
    configMap:
      name: hello-cm
      # items:
      #   - key: index.html
      #     path: index.html