apiVersion: v1
kind: Service
metadata:
  labels:
    run: mynginx
  name: mynginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    run: mynginx
  sessionAffinity: None
  type: NodePort