apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels: 
    app: init
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/data/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/data"
  volumes:
  - name: workdir
    emptyDir: {}
---
apiVersion: v1
kind: Service   
metadata:
  name: init-demo-svc
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    app: init