apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: test
spec:
  containers:
  - name: mycontainer
    image: nginx:latest
    resources:
      limits:
        memory: "400Mi" 

# kubectl describe limitrange -n test