apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: liveness-pod
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    livenessProbe:
      initialDelaySeconds:
      periodSeconds: 5
      exec:
        command:
        - ls
  dnsPolicy: ClusterFirst
  restartPolicy: Never