apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels: 
    app: web
spec:
  volumes:
    - name: mypv-storage
      persistentVolumeClaim:
        claimName: demo-pv-claim
  containers:
    - name: apache-container
      image: httpd:2
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/local/apache2/htdocs"
          name: mypv-storage

# First command: 
# echo "hello world" > /opt/data/index.html