apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myapp
  name: myapp
spec:
  containers:
  - image: nginx:1.25
    name: myapp
    resources:
      requests:
        cpu: "300m"
      limits:
        cpu: "500m"
status: {}
