apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cw-configuration
  name: cw-configuration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cw-configuration
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cw-configuration
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}