apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

# kubectl replace -f mypvc.yaml --force