apiVersion: v1
kind: Pod
metadata:
  name: ng-pod
spec:
  volumes:
    - name: mypv-storage
      persistentVolumeClaim:
        claimName: mypv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mnt/myvol"
          name: mypv-storage