apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: clarusweb-pod
  name: clarusweb-pod
spec:
  containers:
  - image: clarusway/clarusweb:env
    name: clarusweb-pod
    resources: {}
    env:
      - name: COLOR
        valueFrom:
          configMapKeyRef:
            name: myconfig
            key: mycolor
  restartPolicy: Always
