apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <source>
      type tail
      format none
      path /var/log/first.log
      pos_file /var/log/first.log.pos
      tag PHP
    </source>
    
    <source>
      type tail
      format none
      path /var/log/second.log
      pos_file /var/log/second.log.pos
      tag JAVA
    </source>
    
    <match **>
      @type file
      path /var/log/fluent/access
    </match>