apiVersion: v1
kind: Pod
metadata:
  labels:
    test: logs
  name: cw-logging
spec:
  volumes:
    - name: logs-volume
      emptyDir: {}
    - name: fluent-conf
      configMap:
        name: fluentd-config
  containers:
  - name: logs
    image: busybox
    args:
    - /bin/sh
    - -c
    - "mkdir -p /var/log; i=0; while true; do echo \"$i: $(date)\" >> /var/log/first.log; \
      echo \"$(date) INFO $i\" >> /var/log/second.log; i=$((i+1)); sleep 1; done"
    volumeMounts:
      - name: logs-volume
        mountPath: /var/log
  - name: fluentd
    image: k8s.gcr.io/fluentd-gcp:1.30
    env:
    - name: FLUENTD_ARGS
      value: "-c /etc/fluentd-config/fluentd.conf"
    volumeMounts:
      - name: logs-volume
        mountPath: /var/log
      - name: fluent-conf
        mountPath: /etc/fluentd-config
    resources: {}