apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    web: apache
  namespace: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      web: apache
  template:
    metadata:
      labels:
        web: apache
    spec:
      containers:
      - name: apache
        image: httpd:alpine
        ports:
        - containerPort: 80