apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: multi-pod
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: httpd-container
    image: httpd:alpine
    volumeMounts:
    - name: shared-data
      mountPath: /usr/local/apache2/htdocs
  - name: alpine-container
    image: alpine:latest
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: [ "-c", "echo hello world > /pod-data/index.html && sleep 3600" ]
---
apiVersion: v1
kind: Service   
metadata:
  name: two-containers-svc
spec:
  type: NodePort 
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 30001
  selector:
    app: multi-pod
