apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql-pod
  name: mysql-pod
spec:
  containers:
  - image: mysql:latest
    name: mysql-pod
    resources: {}
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Always
